rzk/ChangeLog.md
rzk/package.yaml
rzk/rzk.cabal

This is version contains minor changes, primarily in tools around rzk:
- Add `rzk version` command (see [f1709dc7]( https://github.com/fizruk/rzk/commit/f1709dc7 ));
- Add action to release binaries (see [9286afae]( https://github.com/fizruk/rzk/commit/9286afae ));
- Automate SVG rendering in MkDocs (see [#49]( https://github.com/fizruk/rzk/pull/49 ));
- Read `stdin` when no filepaths are given (see [936c15a3]( https://github.com/fizruk/rzk/commit/936c15a3 ));
- Add Pygments highlighting (see [01c2a017]( https://github.com/fizruk/rzk/commit/01c2a017 ), [cbd656cc]( https://github.com/fizruk/rzk/commit/cbd656cc ), [5220ddf9]( https://github.com/fizruk/rzk/commit/5220ddf9 ), [142ec003]( https://github.com/fizruk/rzk/commit/142ec003 ), [5c7425f2]( https://github.com/fizruk/rzk/commit/5c7425f2 …

Release v0.4.1

---

.github/workflows/ghcjs.yml

This action simplifies further job steps

Use a new action to cache nix store

---

rzk/src/Language/Rzk/Syntax.hs

Fixes #63.
The only important thing is that language has to be specified first (i.e. ` ``` { title = "..." .rzk } ` is not supported).

Recognise code blocks with attributes

---

rzk/ChangeLog.md
rzk/package.yaml
rzk/rzk.cabal
rzk/rzk.nix

This version contains minor improvements:
1. Improve typechecking by trying an easier unification strategy first (see [#76](https://github.com/rzk-lang/rzk/pull/76));
2. Update GitHub Action for Nix (see [#74](https://github.com/rzk-lang/rzk/pull/74)).

Release v0.5.4

---

rzk/package.yaml
rzk/rzk.cabal
rzk/rzk.nix
rzk/src/Rzk/Main.hs
stack.yaml
stack.yaml.lock

To improve support for shells that do not expand globs automatically
such as PowerShell and CMD on Windows

Install and use the glob package

---

rzk/src/Rzk/TypeCheck.hs

This fixes the following bug (missing tope checks):
```rzk
#lang rzk-1
#define Δ²
: (2 × 2) → TOPE
:= \ (t, s) → (s ≤ t)
#define Λ
: Δ² → TOPE
:= \ (t, s) → (s ≡ 0₂) ∨ (t ≡ 1₂)
#define Λ-is-in-Δ²
(A : U)
: (Δ² → A) → (Λ → A)
:= \ f t → f t
#define wrong-Λ
: Δ² → TOPE
:= \ (t, s) → t ≤ s
#define Λ-alt
: (2 × 2) → TOPE
:= \ (t, s) → (t ≡ 0₂) ∨ (s ≡ 1₂)
#define Λ-alt-is-in-wrong-Λ
(A : U)
: (wrong-Λ → A) → (Λ-alt → A)   -- used to be fine before this PR
-- : (( st : (2 × 2) | wrong-Λ st ) → A) → (Λ-alt → A) -- correctly issued a type error
:= \ f t → f t
```

Fix subshape definitions

---

docs/docs/getting-started/changelog.md
rzk/ChangeLog.md
rzk/package.yaml
rzk/rzk.cabal
rzk/rzk.nix

This version contains Unicode and tope logic-related fixes:
1. Fix (add missing checks) for subshapes (see [#85](https://github.com/rzk-lang/rzk/pull/85));
2. Allow to handle wildcards in `rzk` itself (see [#83](https://github.com/rzk-lang/rzk/pull/83));
3. Fix Unicode on machines with non-standard locales (see [#82](https://github.com/rzk-lang/rzk/pull/82));
4. Specify `happy` and `alex` as build tools to fix cabal build from Hackage (see [#80](https://github.com/rzk-lang/rzk/pull/80)).
5. Add configuration for MkDocs plugin for Rzk (see [#79](https://github.com/rzk-lang/rzk/pull/79)).

Release v0.5.5

---

docs/docs/getting-started/changelog.md
rzk/ChangeLog.md
rzk/package.yaml
rzk/rzk.cabal
rzk/rzk.nix

This version fixes the behaviour of glob (see [`77b7cc0`](https://github.com/rzk-lang/rzk/commit/77b7cc0494fe0bfd1c9f1aa83db20f42cfda5794)).

Release v0.5.6

---

rzk/src/Rzk/TypeCheck.hs

This PR contains two fixes, discovered in https://github.com/rzk-lang/sHoTT/pull/30#issuecomment-1729212862:

Fix LEM instances and eta for product cubes

---

docs/docs/getting-started/changelog.md
rzk/ChangeLog.md
rzk/package.yaml
rzk/rzk.cabal
rzk/rzk.nix

This version introduces a proper LSP server with basic support for incremental typechecking
and some minor improvements:
1. LSP server with incremental typechecking (see [#95](https://github.com/rzk-lang/rzk/pull/95));
2. Improve error messages for unclosed `#section` and extra `#end` (see [#91](https://github.com/rzk-lang/rzk/pull/91)).

Release v0.6.0

---

docs/docs/getting-started/changelog.md
rzk/ChangeLog.md
rzk/package.yaml
rzk/rzk.cabal
rzk/rzk.nix

This version contains a minor fix:
- Catch exceptions in the parser, fixing LSP for files where layout resolver fails (see [#99](https://github.com/rzk-lang/rzk/pull/99)).

Release v0.6.1

---

rzk/src/Language/Rzk/VSCode/Handlers.hs
rzk/src/Rzk/Main.hs
rzk/src/Rzk/TypeCheck.hs

Now the actual error message is on top, so there is no need to scroll:

Improve order of information in error messages for LSP

---

rzk/package.yaml
rzk/rzk.cabal
rzk/rzk.nix
rzk/src/Language/Rzk/VSCode/Handlers.hs
rzk/src/Language/Rzk/VSCode/Lsp.hs
stack.yaml
stack.yaml.lock

Uses the previously declared symbols in all previous files (and the currently open one) to provide a list of completion items, displaying their type and definition location.
One known caveat for now is that if there is an error in the current file (e.g.: in the process of defining something), previous  declarations in the same file will not show up. This is a known imperfection in the incremental type checker itself

Text completions

---

docs/docs/getting-started/changelog.md
rzk/ChangeLog.md
rzk/package.yaml
rzk/rzk.cabal
rzk/rzk.nix

This version contains a fix for the command line interface of `rzk`:
- Fix command line `rzk typecheck` (see [#106](https://github.com/rzk-lang/rzk/pull/106))
- Previous version ignored failures in the command line
(the bug was introced when allowing better autocompletion in LSP).

Release v0.6.3

---

docs/docs/getting-started/changelog.md
rzk/ChangeLog.md
rzk/package.yaml
rzk/rzk.cabal
rzk/rzk.nix

This version improves the stucture of the project, in particular w.r.t dependencies:
- Add custom snapshot and explicit lower bounds (see [#108](https://github.com/rzk-lang/rzk/pull/108))
This should in particular help installing via `cabal install` or `stack install`.

Release v0.6.4

---

try-rzk/index.html

With this fix the following template works for playground:
```
https://rzk-lang.github.io/rzk/v0.6.4/playground/?snippet={code}
```
For some reason, the version has to be spelled out (`latest` does not redirect correctly).

Fix snippet param in the Rzk Playground

---

rzk/src/Rzk/Main.hs
rzk/src/Rzk/TypeCheck.hs

In a previous version, `typecheckModule` has been changed to return error messages without failing. This PR now calls `typecheckModules` which will properly handle errors. This affects the behaviour in the playground.

Fix typecheckString behaviour

---

rzk-playground/components/editor/Editor.tsx

This might not be an optimal implementation. @deemp feel free to improve later.

Support snippet/code param in Rzk playground

---

CITATION.cff
docs/docs/getting-started/changelog.md
rzk/ChangeLog.md
rzk/package.yaml
rzk/rzk.cabal

This version contains mostly intrastructure improvements:
- Typecheck using `rzk.yaml` if it exists (see [#119](https://github.com/rzk-lang/rzk/pull/119))
- Update Rzk Playground and Nix Flake (see [#84](https://github.com/rzk-lang/rzk/pull/84))
- Rzk Playground now uses CodeMirror 6 and NextJS
- `miso` dependency is dropped
- GHCJS 9.6 is now used
- Support `snippet={code}` or `code={code}` param (see [#118](https://github.com/rzk-lang/rzk/pull/118))
- Support for `snippet_url={URL}` is temporarily dropped
- Update to GHC 9.6, latest Stackage Nightly, improve Rzk setup, and GitHub Actions (see [#116](https://github.com/rzk-lang/rzk/pull/116))
- Add logging for Rzk Language Server (see [#114](https://github.com/rzk-lang/rzk/pull/114))
Fixes:
- Fix error messages in Rzk Playground (see …

Release v0.6.5

---

.github/workflows/ghc.yml
rzk/Setup.hs
rzk/package.yaml
rzk/rzk.cabal

- Do not run BNFC on Windows (rely on pre-generated files). This is to avoid encoding issues (e.g. see https://github.com/rzk-lang/rzk/actions/runs/6372824473/job/17295991361#step:3:5176)
- Fix an issue with the build on macOS (using `-optP-Wno-nonportable-include-path` option advised in https://github.com/haskell/cabal/issues/4739#issuecomment-359209133).
Note that for Windows this is a temporary fix. Ideally, we would need BNFC to handle Unicode on Windows correctly or fix it somehow in the `Setup.hs`.

Fix windows build

---

CITATION.cff
docs/docs/CHANGELOG.md
docs/docs/index.md
docs/mkdocs.yml
rzk/ChangeLog.md
rzk/package.yaml
rzk/rzk.cabal

- Fix builds on Windows (and macOS) (see [#121](https://github.com/rzk-lang/rzk/pull/121))

Release v0.6.6

---

CITATION.cff
README.md
docs/docs/CHANGELOG.md
docs/docs/getting-started/install.md
rzk/ChangeLog.md
rzk/package.yaml
rzk/rzk.cabal

- Fix build on some systems (fix `BNFC:bnfc` executable dependency, see [#125](https://github.com/rzk-lang/rzk/pull/125))
- Improve Rzk Playground (see [#124](https://github.com/rzk-lang/rzk/pull/124) by @deemp):
- Add `snippet_url` parameter
- Migrated from NextJS to Vite
- Use `setText` on `params` attribute
- Slightly improve documentation:
- Add links to Rzk Zulip (see [#131](https://github.com/rzk-lang/rzk/pull/131))
- Add `cabal update` to instructions (see [`3aa8fd3`](https://github.com/rzk-lang/rzk/commit/3aa8fd38902fc8cbb29f86122410d24398a15b0b))

Release v0.6.7

---

.github/workflows/ghcjs.yml

This should make the following link work properly:
<https://rzk-lang.github.io/rzk/latest/playground/>

Push Rzk Playground to latest (since it's not replicated by default)

---

README.md
flake.lock
flake.nix
hie.yaml
nix/ghcjs.nix
rzk/app/Main.hs
rzk/package.yaml
rzk/rzk.cabal
rzk/src/Language/Rzk/VSCode/Config.hs
rzk/src/Language/Rzk/VSCode/Env.hs
rzk/src/Language/Rzk/VSCode/Handlers.hs
rzk/src/Language/Rzk/VSCode/Lsp.hs
rzk/src/Rzk/Format.hs
rzk/src/Rzk/Main.hs
stack.yaml
stack.yaml.lock

This implements a very basic formatter that scans the lexical tokens for some known patterns and applies text edits to have them adhere to the [style guide](https://rzk-lang.github.io/sHoTT/STYLEGUIDE/). The code is still in an early stage and can definitely be improved a lot, so a code review would be tremendously helpful.
Also, an issue was discovered with LSP's VFS wherein it includes carriage return (`\r`) character on Windows, causing issues with the parser. A workaround has been added (`filter (/= '\r')`), but can probably be improved.
- Adds a space after the opening parenthesis to help with the [code tree structure](https://rzk-lang.github.io/sHoTT/STYLEGUIDE/#the-tree-structure-of-constructions)
- Puts the definition conclusion (type, starting with `:`) and construction (body, …

Formatter - initial basic implementation

---

CITATION.cff
docs/docs/CHANGELOG.md
rzk/ChangeLog.md
rzk/package.yaml
rzk/rzk.cabal
stack.yaml
stack.yaml.lock

Major changes:
- Add an experimental `rzk format` command (by [Abdelrahman Abounegm](https://github.com/aabounegm), with feedback by [Fredrik Bakke](https://github.com/fredrik-bakke) (see [sHoTT#142](https://github.com/rzk-lang/sHoTT/pull/142)) and [Nikolai Kudasov](https://github.com/fizruk)):
- Automatically format files, partially automating the [Code Style of the sHoTT project](https://rzk-lang.github.io/sHoTT/STYLEGUIDE/)
- Notable features:
- Adds a space after the opening parenthesis to help with the [code tree structure](https://rzk-lang.github.io/sHoTT/STYLEGUIDE/#the-tree-structure-of-constructions)
- Puts the definition conclusion (type, starting with `:`) and construction (body, starting with `:=`) on new lines
- Adds a space after the `\` of a lambda term and around binary …

Bump version and update changelogs (and CITATION.cff)

---

CITATION.cff
docs/docs/CHANGELOG.md
rzk/ChangeLog.md
rzk/package.yaml
rzk/rzk.cabal

- Fix default build to include Rzk Language Server (`rzk lsp`) (see [`9b78a15`](https://github.com/rzk-lang/rzk/commit/9b78a15c750699afa93c4dab3735c2aa31e6faac));
- Apply formatting to `recId.rzk.md` example (see [`4032724`](https://github.com/rzk-lang/rzk/commit/40327246954332f40cd82c48d102bf4257ad719e));

Release v0.7.1

---

rzk/src/Rzk/Format.hs

Replaced `setDifference` with `stripInfix` to fix a problem where any subsequence of the "needle" set would be removed

Fix extra space after open parens in formatter

---

CITATION.cff
rzk/ChangeLog.md
rzk/package.yaml
rzk/rzk.cabal

Fixes:
- Fixes for `rzk format`:
- Fix extra space after open parens in formatter (see [#155](https://github.com/rzk-lang/rzk/pull/155));
- Replace line string content with tokens when checking open parens (see [#156](https://github.com/rzk-lang/rzk/pull/156));
- Throw an error when `rzk.yaml`'s `include` is empty (see [#154](https://github.com/rzk-lang/rzk/pull/154));
Changes to the Rzk website:
- Support multiple languages in the documentation (see [#150](https://github.com/rzk-lang/rzk/pull/150));
- English is the default;
- Russian documentation is partially translated and is available at <http://rzk-lang.github.io/rzk/ru/>;
- Add a blog (see [#153](https://github.com/rzk-lang/rzk/pull/153) and [`e438820`](https://github.com/rzk-lang/rzk/commit/e4388202cea59531903c4c24b939841b2771ceb7) …

Release v0.7.2

---

rzk/src/Rzk/Format.hs

to avoid overlapping with possible unicode edits
This should fix the failing test in #157

Split the space edits around bin ops into 2

---

CITATION.cff
rzk/ChangeLog.md
rzk/package.yaml
rzk/rzk.cabal

Fixes:
- Fix overlapping edits in the formatter, hopefully making it idempotent (see [#160](https://github.com/rzk-lang/rzk/pull/160));
- Fix formatter crashing the language server (see [#161](https://github.com/rzk-lang/rzk/pull/161));
- Avoid unnecessary typechecking when semantics of a file has not changed (see [#159](https://github.com/rzk-lang/rzk/pull/159));
- Stop typechecking after the first parse error (avoid invalid cache) (see [`68ab0b4`](https://github.com/rzk-lang/rzk/commit/68ab0b4dd3d627756e10adb55cb16845b08d09d9));
Other:
- Add unit tests for the formatter (see [#157](https://github.com/rzk-lang/rzk/pull/157));

Release v0.7.3

---

docs/docs/en/posts/2023-12-24-formatter.rzk.md

Adds the required `#lang rzk-1` preamble and unmarks the duplicate code block as Rzk code (to prevent "duplicate identifier" errors)

Blog hotfix: formatter post

---

rzk/src/Language/Rzk/VSCode/Env.hs
rzk/src/Language/Rzk/VSCode/Handlers.hs
rzk/src/Rzk/TypeCheck.hs

By adding type errors to the cache and check them when confirming if the file has changed

Fix skipping to typechecking the next file if the current has an error

---

CITATION.cff
rzk/ChangeLog.md
rzk/package.yaml
rzk/rzk.cabal

Fixes:
- Fix caching in Rzk Language Server, especially in presence of errors (see [#167](https://github.com/rzk-lang/rzk/pull/167))
- Fix CI for the Rzk Playground (see [#174](https://github.com/rzk-lang/rzk/pull/174))
This release also contains minor refactoring (see [#165](https://github.com/rzk-lang/rzk/pull/165)) and a typo fix (see [#171](https://github.com/rzk-lang/rzk/pull/171)).

Release v0.7.4

---

rzk/src/Language/Rzk/VSCode/Handlers.hs

Some hacks to report properly location of parse errors (instead of at the start of the file):
Examples:

Report correct location for parse error diagnostics (Language Server)

---

flake.lock
flake.nix

Upgraded the nixpkgs revision to more recent to include fixes (nixos/nixpkgs#258280) to most haskell packages not building on aarch64-darwin. 
Also updated ghc to 9.6.3 as it seems 9.6.2 was dropped from nixpkgs along the way(?)

Fix build of nix flake on aarch64-darwin

---

.github/workflows/ghc.yml
.github/workflows/ghcjs.yml
.github/workflows/mkdocs.yml
.github/workflows/release.yml

Fix the build by switcing the build to `macos-12` instead of `macos-latest`, since the latter does not have Stack (yet). Thanks to @deemp for the pointer!
Also update all actions.

Fix CI: update all actions

---

rzk/app/Main.hs
rzk/package.yaml
rzk/rzk.cabal
rzk/src/Language/Rzk/VSCode/Handlers.hs
stack.yaml
stack.yaml.lock

Support newer lsp

---

CITATION.cff
rzk/ChangeLog.md
rzk/package.yaml
rzk/rzk.cabal

Minor changes:
- Suport syntax sugar for nested Σ-types (see [#183](https://github.com/rzk-lang/rzk/pull/183))
- Improve error reporting (see [#176](https://github.com/rzk-lang/rzk/pull/176) and [#179](https://github.com/rzk-lang/rzk/pull/179))
Fixes:
- Support newer `lsp` (specifically, `lsp-2.7.0.0`, see [#188](https://github.com/rzk-lang/rzk/pull/188))
- Fix CI (see [#184](https://github.com/rzk-lang/rzk/pull/184))
- Fix build of nix flake on aarch64-darwin (see [#181](https://github.com/rzk-lang/rzk/pull/181))
- Small documentation fixes (see [#178](https://github.com/rzk-lang/rzk/pull/178))

Release v0.7.5
